
modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
[[mods]]
modId="examplemod"
version="${file.jarVersion}"
displayName="Example Mod"
logoFile="logo.png"
credits="Thanks for"
authors="BioAst"
description='''
'''

[[dependencies.examplemod]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
